spring:
  devtools:
    add-properties: false
  main:
    banner-mode: off
  thymeleaf:
    check-template-location: false

# Datasource
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/unified_auth_management_system?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    jpa:
      show-sql: true

# Spring Security
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          client-1:
#            registration:
#              client-id: test-client
#              client-secret: "{bcrypt}$2a$10$Kap06i8TyIcJELoy3GKpTepH0kHaWZS0WUv/yCkBe6Z7CJa9t5pmS"
#              client-authentication-methods:
#                - client_secret_basic
#              authorization-grant-types:
#                - password
#                - client_credentials
#                - authorization_code
#                - refresh_token
#              redirect-uris:
#                - http://127.0.0.1:8082/login/oauth2/code/spring
#              scopes:
#                - read
#                - write
#                - openid
#            require-authorization-consent: true
#            token:
#              access-token-time-to-live: 300s

# Logging
logging:
  level:
    org:
      springframework:
        security: trace

server:
  port: 9192

# Properties
DB_HOST: localhost
DB_PORT: 3306
DB_USERNAME: root
DB_PASSWORD: HingePay.2018$